
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T10:58:14.757-05:00
 * Generated source version: 3.3.5
 */

@WebFault(name = "FCVException", targetNamespace = "http://tempuri.org/")
public class FCVException_Exception extends Exception {

    private org.tempuri.FCVException fcvException;

    public FCVException_Exception() {
        super();
    }

    public FCVException_Exception(String message) {
        super(message);
    }

    public FCVException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FCVException_Exception(String message, org.tempuri.FCVException fcvException) {
        super(message);
        this.fcvException = fcvException;
    }

    public FCVException_Exception(String message, org.tempuri.FCVException fcvException, java.lang.Throwable cause) {
        super(message, cause);
        this.fcvException = fcvException;
    }

    public org.tempuri.FCVException getFaultInfo() {
        return this.fcvException;
    }
}
