package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T10:58:14.853-05:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ResultadoDataBank")
@XmlSeeAlso({ObjectFactory.class})
public interface ResultadoDataBank {

    @WebMethod
    @RequestWrapper(localName = "ingresoResultados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IngresoResultados")
    @ResponseWrapper(localName = "ingresoResultadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IngresoResultadosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String ingresoResultados(

        @WebParam(name = "transmisionLISResult", targetNamespace = "")
        java.lang.String transmisionLISResult
    ) throws FCVException_Exception;
}
