package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T10:58:14.912-05:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "ResultadoBancoSangre",
                  wsdlLocation = "file:/C:/Users/dpcampillo/Documents/dev-projects/wsconsumer/src/main/resources/wsdl/ResultadoDataBank.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class ResultadoBancoSangre extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ResultadoBancoSangre");
    public final static QName ResultadoBancoSangreSoap = new QName("http://tempuri.org/", "ResultadoBancoSangreSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/dpcampillo/Documents/dev-projects/wsconsumer/src/main/resources/wsdl/ResultadoDataBank.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ResultadoBancoSangre.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/dpcampillo/Documents/dev-projects/wsconsumer/src/main/resources/wsdl/ResultadoDataBank.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ResultadoBancoSangre(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResultadoBancoSangre(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResultadoBancoSangre() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ResultadoBancoSangre(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ResultadoBancoSangre(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ResultadoBancoSangre(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ResultadoDataBank
     */
    @WebEndpoint(name = "ResultadoBancoSangreSoap")
    public ResultadoDataBank getResultadoBancoSangreSoap() {
        return super.getPort(ResultadoBancoSangreSoap, ResultadoDataBank.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResultadoDataBank
     */
    @WebEndpoint(name = "ResultadoBancoSangreSoap")
    public ResultadoDataBank getResultadoBancoSangreSoap(WebServiceFeature... features) {
        return super.getPort(ResultadoBancoSangreSoap, ResultadoDataBank.class, features);
    }

}
